# Selecting the best model with best hyperparameters

---
### Author :  Muhammad Ali Saagar

**Python Developer • Data Science • AI/ML Engineer**

#### 🔗 Connect With Me

[![GitHub](https://img.shields.io/badge/GitHub-Profile-181717?style=for-the-badge\&logo=github)](https://github.com/AliMuhammad78)
[![LinkedIn](https://img.shields.io/badge/LinkedIn-Profile-0A66C2?style=for-the-badge\&logo=linkedin)](https://www.linkedin.com/in/muhammad-ali-91294a290)
[![Kaggle](https://img.shields.io/badge/Kaggle-Profile-20BEFF?style=for-the-badge\&logo=kaggle)](https://www.kaggle.com/ali98muhammad45)
[![YouTube](https://img.shields.io/badge/YouTube-Channel-FF0000?style=for-the-badge\&logo=youtube)](https://www.youtube.com/@TechyBits20121)
[![Email](https://img.shields.io/badge/Email-Contact-D14836?style=for-the-badge\&logo=gmail)](mailto:alisaagar86@gmail.com)

---

### Acknowledgement

> Most of the examples in this notebook are based on the excellent tutorials by **Dr. Muhammad Aammar Tufail (Codanics)**. I sincerely thank him for sharing his knowledge and practical examples.

 [![GitHub](https://img.shields.io/badge/GitHub-Profile-181717?style=for-the-badge\&logo=github)](https://github.com/AammarTufail)
[![LinkedIn](https://img.shields.io/badge/LinkedIn-Profile-0A66C2?style=for-the-badge\&logo=linkedin)](https://www.linkedin.com/in/dr-muhammad-aammar-tufail-02471213b/)
[![Kaggle](https://img.shields.io/badge/Kaggle-Profile-20BEFF?style=for-the-badge\&logo=kaggle)](https://www.kaggle.com/muhammadaammartufail)
[![YouTube](https://img.shields.io/badge/YouTube-Channel-FF0000?style=for-the-badge\&logo=youtube)](https://www.youtube.com/@codanics)

In [16]:
import pandas as pd
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import LabelEncoder , MinMaxScaler , StandardScaler 
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.metrics import mean_absolute_error , mean_squared_error  , r2_score 
from sklearn.linear_model import LinearRegression 
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor , GradientBoostingRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

In [2]:
df = sns.load_dataset("tips")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [3]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

# Regression Tasks

In [5]:
X = df.drop('tip' , axis= 1)
y=df['tip']

le = LabelEncoder() 

X['sex'] = le.fit_transform(X['sex'])
X['smoker'] = le.fit_transform(X['smoker'])
X['day'] = le.fit_transform(X['day'])
X['time'] = le.fit_transform(X['time'])

### Best model on the basis of MAE

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


models = {
    "Linear Regression " : LinearRegression() ,
    "Support Vector Machine " : SVR() , 
    "Decision Tree " :DecisionTreeRegressor(), 
    "Random Forest" : RandomForestRegressor() , 
    "KNN" : KNeighborsRegressor(),
    "Gradient Boosting " : GradientBoostingRegressor(),
    "XGB Regressor" : XGBRegressor()
}

model_scores = []

for name , model in models.items():
    model.fit(X_train , y_train)

    y_pred = model.predict(X_test)

    metric = mean_absolute_error(y_test , y_pred)
    model_scores.append((name , metric))

# model_scores

# sorted models 
sorted_models = sorted(model_scores ,  key=lambda x: x[1],  reverse = False)

for model in sorted_models: 
    print(f"Mean absolute error for { model[0] } is {model[1] : .2f} ")

Mean absolute error for Support Vector Machine  is  0.57
Mean absolute error for Linear Regression  is  0.67
Mean absolute error for XGB Regressor is  0.67
Mean absolute error for Gradient Boosting  is  0.72
Mean absolute error for KNN is  0.73
Mean absolute error for Random Forest is  0.77
Mean absolute error for Decision Tree  is  0.83

### Best model based on R2 score

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


models = {
    "Linear Regression " : LinearRegression() ,
    "Support Vector Machine " : SVR() , 
    "Decision Tree " :DecisionTreeRegressor(), 
    "Random Forest" : RandomForestRegressor() , 
    "KNN" : KNeighborsRegressor(),
    "Gradient Boosting " : GradientBoostingRegressor(),
    "XGB Regressor" : XGBRegressor()
}

model_scores = []

for name , model in models.items():
    model.fit(X_train , y_train)

    y_pred = model.predict(X_test)

    metric = r2_score(y_test , y_pred)
    model_scores.append((name , metric))

# model_scores

# sorted models 
# sorted_models = sorted(model_scores ,  key=lambda x: x[1],  reverse = False)
# if you put reverse = True here , then last will appear at top , that will be better 

sorted_models = sorted(model_scores ,  key=lambda x: x[1],  reverse = True)


for model in sorted_models: 
    print(f"r2_score  for { model[0] } is {model[1] : .2f} ")

r2_score  for Support Vector Machine  is  0.57
r2_score  for Linear Regression  is  0.44
r2_score  for XGB Regressor is  0.41
r2_score  for Gradient Boosting  is  0.35
r2_score  for KNN is  0.33
r2_score  for Random Forest is  0.28
r2_score  for Decision Tree  is -0.20

### Based on Mean Squared error (MSE)

In [17]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


models = {
    "Linear Regression " : LinearRegression() ,
    "Support Vector Machine " : SVR() , 
    "Decision Tree " :DecisionTreeRegressor(), 
    "Random Forest" : RandomForestRegressor() , 
    "KNN" : KNeighborsRegressor(),
    "Gradient Boosting " : GradientBoostingRegressor(),
    "XGB Regressor" : XGBRegressor()
}

model_scores = []

for name , model in models.items():
    model.fit(X_train , y_train)

    y_pred = model.predict(X_test)

    metric = mean_squared_error(y_test , y_pred)
    model_scores.append((name , metric))

# model_scores

# sorted models 
sorted_models = sorted(model_scores ,  key=lambda x: x[1],  reverse = False)

for model in sorted_models: 
    print(f"Mean squared error for { model[0] } is {model[1] : .2f} ")

Mean squared error for Support Vector Machine  is  0.54
Mean squared error for Linear Regression  is  0.69
Mean squared error for XGB Regressor is  0.74
Mean squared error for Gradient Boosting  is  0.81
Mean squared error for KNN is  0.84
Mean squared error for Random Forest is  1.04
Mean squared error for Decision Tree  is  1.34

---

# Selecting best model on the basis of Diamond dataset

In [18]:
df = sns.load_dataset("diamonds")
df.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [21]:
X = df.drop("price" , axis=1)
y= df['price']

In [19]:
df.dtypes

carat       float64
cut        category
color      category
clarity    category
depth       float64
table       float64
price         int64
x           float64
y           float64
z           float64
dtype: object

In [22]:
# encoding 
# cut        category
# color      category
# clarity    category
le  = LabelEncoder()
X['cut'] = le.fit_transform(X['cut'])
X['color'] = le.fit_transform(X['color'])
X['clarity'] = le.fit_transform(X['clarity'])

### Best model on the basis of MAE

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


models = {
    "Linear Regression " : LinearRegression() ,
    "Support Vector Machine " : SVR() , 
    "Decision Tree " :DecisionTreeRegressor(), 
    "Random Forest" : RandomForestRegressor() , 
    "KNN" : KNeighborsRegressor(),
    "Gradient Boosting " : GradientBoostingRegressor(),
    "XGB Regressor" : XGBRegressor()
}

model_scores = []

for name , model in models.items():
    model.fit(X_train , y_train)

    y_pred = model.predict(X_test)

    metric = mean_absolute_error(y_test , y_pred)
    model_scores.append((name , metric))

# model_scores

# sorted models 
sorted_models = sorted(model_scores ,  key=lambda x: x[1],  reverse = False)

for model in sorted_models: 
    print(f"Mean absolute error for { model[0] } is {model[1] : .2f} ")

Mean absolute error for Random Forest is  268.44
Mean absolute error for XGB Regressor is  277.94
Mean absolute error for Decision Tree  is  351.22
Mean absolute error for Gradient Boosting  is  364.86
Mean absolute error for KNN is  480.77
Mean absolute error for Linear Regression  is  858.71
Mean absolute error for Support Vector Machine  is  2747.33

> It is took 17m  time because of less resources in machin 
>
> so other error can be seen by just changing the name of error

---

# Hyperparametrized tuning

In [ ]:
%%time
# Create a dictionaries of list of models to evaluate performance with hyperparameters
models = { 
          'LinearRegression' : (LinearRegression(), {}),
          'SVR' : (SVR(), {'kernel': ['rbf', 'poly', 'sigmoid']}),
          'DecisionTreeRegressor' : (DecisionTreeRegressor(), {'max_depth': [None, 5, 10]}),
          'RandomForestRegressor' : (RandomForestRegressor(), {'n_estimators': [10, 100]}),
          'KNeighborsRegressor' : (KNeighborsRegressor(), {'n_neighbors': np.arange(3, 100, 2)}),
          'GradientBoostingRegressor' : (GradientBoostingRegressor(), {'n_estimators': [10, 100]}),
          'XGBRegressor' : (XGBRegressor(), {'n_estimators': [10, 100]}),          
          }

# train and predict each model with evaluation metrics as well making a for loop to iterate over the models

for name, (model, params) in models.items():
    # create a pipline
    pipeline = GridSearchCV(model, params, cv=5)
    
    # fit the pipeline
    pipeline.fit(X_train, y_train)
    
    # make prediction from each model
    y_pred = pipeline.predict(X_test)
    
      
    # print the performing metric
    print(name, 'MSE: ', mean_squared_error(y_test, y_pred))
    print(name, 'R2: ', r2_score(y_test, y_pred))
    print(name, 'MAE: ', mean_absolute_error(y_test, y_pred))
    print('\n')

In [ ]:
%%time
# Note, ensure to give more time to run this cell
# Create a dictionaries of list of models to evaluate performance with hyperparameters
from sklearn.model_selection import RandomizedSearchCV
models = { 
          'LinearRegression' : (LinearRegression(), {}),
          'SVR' : (SVR(), {'kernel': ['rbf', 'poly', 'sigmoid'], 'C': [0.1, 1, 10], 'gamma': [1, 0.1, 0.01], 'epsilon': [0.1, 0.01, 0.001]}),
          'DecisionTreeRegressor' : (DecisionTreeRegressor(), {'max_depth': [None, 5, 10], 'splitter': ['best', 'random']}),
          'RandomForestRegressor' : (RandomForestRegressor(), {'n_estimators': [10, 100, 1000], 'max_depth': [None, 5, 10]}),
          'KNeighborsRegressor' : (KNeighborsRegressor(), {'n_neighbors': np.arange(3, 100, 2), 'weights': ['uniform', 'distance']}),
          'GradientBoostingRegressor' : (GradientBoostingRegressor(), {'loss': ['ls', 'lad', 'huber', 'quantile'], 'n_estimators': [10, 100, 1000]}),
          'XGBRegressor' : (XGBRegressor(), {'n_estimators': [10, 100, 1000], 'learning_rate': [0.1, 0.01, 0.001]}),          
          }

# train and predict each model with evaluation metrics as well making a for loop to iterate over the models

for name, (model, params) in models.items():
    # create a pipline
    pipeline = RandomizedSearchCV(model, params, cv=5)
    
    # fit the pipeline
    pipeline.fit(X_train, y_train)
    
    # make prediction from each model
    y_pred = pipeline.predict(X_test)
    
      
    # print the performing metric
    print(name, 'MSE: ', mean_squared_error(y_test, y_pred))
    print(name, 'R2: ', r2_score(y_test, y_pred))
    print(name, 'MAE: ', mean_absolute_error(y_test, y_pred))
    print('\n')

# **Add preprocessor inside the pipeline**

In [ ]:
# make a preprocessor

preprocessor = ColumnTransformer(
    transformers=['numeric_scaling', StandardScaler(), ['total_bill', 'size']], remainder='passthrough')


# Create a dictionaries of list of models to evaluate performance with hyperparameters
models = { 
          'LinearRegression' : (LinearRegression(), {}),
          'SVR' : (SVR(), {'kernel': ['rbf', 'poly', 'sigmoid'], 'C': [0.1, 1, 10], 'gamma': [1, 0.1, 0.01], 'epsilon': [0.1, 0.01, 0.001]}),
          'DecisionTreeRegressor' : (DecisionTreeRegressor(), {'max_depth': [None, 5, 10], 'splitter': ['best', 'random']}),
          'RandomForestRegressor' : (RandomForestRegressor(), {'n_estimators': [10, 100, 1000], 'max_depth': [None, 5, 10]}),
          'KNeighborsRegressor' : (KNeighborsRegressor(), {'n_neighbors': np.arange(3, 100, 2), 'weights': ['uniform', 'distance']}),
          'GradientBoostingRegressor' : (GradientBoostingRegressor(), {'loss': ['ls', 'lad', 'huber', 'quantile'], 'n_estimators': [10, 100, 1000]}),
          'XGBRegressor' : (XGBRegressor(), {'n_estimators': [10, 100, 1000], 'learning_rate': [0.1, 0.01, 0.001]}),          
          }

# train and predict each model with evaluation metrics as well making a for loop to iterate over the models

for name, (model, params) in models.items():
    # create a pipline with preprocessor
    pipeline = Pipeline(steps=[('preprocessor', preprocessor), ('model', model)])   
    
    # make a grid search cv to tune the hyperparameter
    grid_search = GridSearchCV(pipeline, params, cv=5)
    
    
    # fit the pipeline
    grid_search.fit(X_train, y_train)
    
    # make prediction from each model
    y_pred = grid_search.predict(X_test)
    
      
    # print the performing metric
    print(name, 'MSE: ', mean_squared_error(y_test, y_pred))
    print(name, 'R2: ', r2_score(y_test, y_pred))
    print(name, 'MAE: ', mean_absolute_error(y_test, y_pred))
    print('\n')

---
---

---
---

# Classifiers:

In [24]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score, KFold
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

# dont show warnings
import warnings
warnings.filterwarnings('ignore')

# Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Create a dictionary of classifiers to evaluate
classifiers = {
    'Logistic Regression': LogisticRegression(),
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'SVM': SVC(),
    'KNN': KNeighborsClassifier()
}

# Perform k-fold cross-validation and calculate the mean accuracy
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

for name, classifier in classifiers.items():
    scores = cross_val_score(classifier, X, y, cv=kfold)
    accuracy = np.mean(scores)
    print("Classifier:", name)
    print("Mean Accuracy:", accuracy)
    print()

Classifier: Logistic Regression
Mean Accuracy: 0.9733333333333334

Classifier: Decision Tree
Mean Accuracy: 0.9533333333333335

Classifier: Random Forest
Mean Accuracy: 0.9600000000000002

Classifier: SVM
Mean Accuracy: 0.9666666666666668

Classifier: KNN
Mean Accuracy: 0.9733333333333334